version: '3.8'

services:

  react:
    image: node:14
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npm run build && npx serve -s build"
    ports:
      - "3000:5000"

  flask_api:
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017

  mongodb:
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data: