version: '3.8'
services:
  react:
    image: node:14
    volumes:
      - ./path/to/your/react-app:/app
    working_dir: /app
    command: sh -c "npm install && npm run build && npx serve -s build"
    ports:
      - "3000:5000"

  flask_api:
    build: ./path/to/your/flask/app
    volumes:
      - ./path/to/your/flask/app:/app
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
      - elasticsearch
    environment:
      - DATABASE_URL=postgres://user:password@postgres/dbname
      - REDIS_URL=redis://redis:6379
      - ELASTICSEARCH_URL=http://elasticsearch:9200

  redis:
    image: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # AMQP protocol
      - "15672:15672" # management interface

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname

  elasticsearch:
    image: elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./path/to/your/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - "3001:3000"

  graylog:
    image: graylog/graylog:3.3
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_PASSWORD_SHA2=yoursha256hash
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    ports:
      - "9000:9000"
      - "12201:12201"
      - "1514:1514"

volumes:
  postgres_data:
